config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/auth/destroy' => 'sessions#destroy', as: 'destroy_session'

  resources :universes, only: [:index, :new, :create] do
    get 'preview'
  end

  resources :universes, path: '/' do
    get 'calendar', on: :member

    resources :people do
      get 'avatar', on: :member
      get 'generic_avatar', on: :member
    end

    resources :organizations, path: '/o' do
      get 'calendar', on: :member
      resources :milestones
      resources :journals
      resources :events
      resources :todos do
        post 'relate', on: :collection
        post 'unrelate', on: :collection
        post 'assign', on: :member
        post 'unassign', on: :member
      end
    end
  end
end

app/views/shared/_actionbar.html.erb
<% if current_universe %>
  <section class="actionbar" data-turbo="false">
    <%= action_link current_universe, icon('planet-ringed'), current_universe.name, current_universe.bg, current_universe.fg %>
    <%= action_link universe_people_path(current_universe), icon('users'), 'People', current_universe.bg, current_universe.fg %>
    <%= action_link calendar_universe_path(current_universe), icon('calendar-alt'), 'Calendar', current_universe.bg, current_universe.fg , data: { turbo: false } %>
    <%= action_link universe_organizations_path(current_universe), icon('users-class'), 'Organizations', current_universe.bg, current_universe.fg %>
    <% if current_organization %>
      <%= action_link [current_universe, current_organization], icon('house'), current_organization.name, current_organization.bg, current_organization.fg %>
      <%= action_link calendar_universe_organization_path(current_universe, current_organization), icon('calendar'), 'Calendar', current_organization.bg, current_organization.fg , data: { turbo: false } %>
      <%= action_link current_container_route_for(:todos), icon('clipboard-list'), 'ToDos', current_organization.bg, current_organization.fg  %>
    <% end %>
  </section>
<% end %>

app/views/shared/_calendar.html.erb
<div id="calendar"></div>

<script>
var calendar = null
var calendarEl = document.getElementById('calendar');
if(calendarEl) {
  calendar = new FullCalendar.Calendar(calendarEl, {
    headerToolbar: {
      start: 'title',
      center: 'dayGridMonth timeGridWeek',
      end: 'today prev,next'
    },
    height: '80vh',
    initialView: 'timeGridWeek',
    events: '<%= url %>'
  });
  calendar.render();
}
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%= image_tag 'logo-inverse.png' %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="primaryNavbar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="primaryNavbar" class="navbar-menu">
    <div class="navbar-start">
      <% if current_user %>
        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= icon('planet-ringed') %> &nbsp; Your Universes
        </a>

        <div class="navbar-dropdown">
          <% current_user.universes.each do |u| %>
            <%= link_to u.name, u, class: 'navbar-item' %>
          <% end %>
        </div>
      </div>
      <% end %>

      <% if super_admin? %>
        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= icon('wrench') %> &nbsp; System Setup
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Manage Universes", universes_path, class: 'navbar-item' %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="navbar-end">
      <% if current_user %>
        <li class="navbar-item">
          <%= link_to 'Log Out', destroy_session_path, class: 'button is-light' %>
        </li>
      <% else %>
        <div class="navbar-item">
          <div class="buttons">
            <a class="button is-primary">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light">
              Log in
            </a>
          </div>
        </div>
      <% end %>

      <% if flash.empty? %>
          <div class="navbar-item">
            <i class="fas fa-bell"></i> &nbsp; &nbsp;
          </li>
        <% else %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              (<%= flash.count %>) &nbsp; <i class="fas fa-bell"></i>
            </a>

            <div class="navbar-dropdown">
              <% flash.each do |k, msg| %>
                <div class="alert alert-dark">
                  <%= msg %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</nav>